name: IslandDefender
version: '${project.version}'
main: me.firedragon5.islanddefender.IslandDefender
api-version: '1.20'


permissions:
  islanddefender.mines:
    description: Allows access to the mines commands
    default: true

  islanddefender.mines.admin:
    description: Allows access to the mines admin commands
    default: op

  islanddefender.staff:
    description: Allows access to the staff commands
    default: op

  islanddefender.staffchat:
    description: Allows access to the staff chat commands
    default: op

  islanddefender.clan:
    description: Allows access to the clan commands
    default: true

  islanddefender.admin:
    description: Allows access to the admin commands
    default: op

