name: IslandDefender
version: '${project.version}'
main: me.firedragon5.islanddefender.IslandDefender
api-version: '1.20'

commands:
  clan:
    aliases: [ clan, c ]
    description: Clan commands

  staffchat:
    aliases: [ staffchat, sc ]
    description: Staff chat commands

  staff:
    aliases: [ staff, s ]
    description: Staff commands

  mine:
    aliases: [ mines, m ]
    description: Mines commands